# Ignored by GitHub:
# - source: <your pages repo>
# - destination: <the build dir>
# - lsi: false
# - pygments: true
#

# List of directories to exclude in Jekyll
exclude: []

# Add Support to Pygments Syntax Highlighter
pygments: true

# Custom data, available through {{ site.<variable> }}
# none so far ^^
